version: "3.9"
services:
  frontend:
    command: bash -c "yarn && yarn serve"
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000

  backend:
    command: bash -c "yarn && yarn run start:dev"
    environment:
      - PORT=8000
      - NODE_ENV=development
      - MONGO_ROOT_USERNAME=root
      - MONGO_ROOT_PASSWORD=rootpassword
      - MONGO_HOSTNAME=mongodb
      - MONGO_DATABASE=test
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - back-tier

volumes:
  mongodb_data_container: