version: "3.9"
services:
  frontend:
    image: 'node:14'
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend/
    networks:
      - back-tier


  backend:
    image: 'node:14'
    command: bash -c "yarn && yarn start"
    volumes:
      - ./backend:/backend
    working_dir: /backend/
    environment:
      - NODE_ENV=development
      - PORT=8000
    ports:
      - 8000:8000
    networks:
      - back-tier
    restart: always


  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - back-tier
    ports:
      - 80:80
    
networks:
    back-tier:
        driver: bridge
