version: "3.9"
services:
  frontend:
    image: 'node:14'
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend/
    networks:
      - back-tier


  backend:
    command: bash -c "yarn start"
    environment:
      - NODE_ENV=development
      - PORT=8000
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - back-tier
    
networks:
    back-tier:
        driver: bridge